- name: CCP | Cleanup artifactory directories
  file: path="{{ ccp_release_dir }}" state=absent

- name: CCP | Cleanup artifactory directories
  file: path="{{ ccp_release_dir }}" state=directory

- name: CCP | Synchronize artifacts
  synchronize:
    src: "{{ local_artifactory_dir }}/{{ item }}"
    dest: "{{ ccp_release_dir }}"
    mode: push
    recursive: yes
  register: get_task
  until: get_task|success
  retries: 10
  delay: "{{ retry_stagger | random + 10 }}"
  with_items:
    - "{{ pip_packages_folder }}"
    - "{{ ccp_repositories_path }}"
    - "{{ ccp_path }}"