- name: CCP | Ensure configuration folder exist
  file: path="{{ ccp_release_dir }}/{{ ccp_config_file | dirname }}" state=directory

- name: CCP | Create build configuration
  template: src=ccp.conf.j2 dest="{{ ccp_release_dir }}/{{ ccp_config_file }}"