- name: Check if Gluster installed
  shell: rpm -qa | grep -q {{ item }}
  with_items:
    - glusterfs-client
    - glusterfs-fuse
  register: package_installed
  failed_when: package_installed.rc != 0
  when: ansible_os_family == "RedHat"