- name: Create mount point
  file:
    path: "{{ glusterfs_mount_point }}"
    state: directory
    mode: 0755
    owner: "{{ glusterfs_mount_point_user_id }}"
    group: "{{ glusterfs_mount_point_group_id }}"

