---
# defaults file for docker_registry
# certificates options
registry_certs_path: "/etc/ssl/certs"
container_address: "{{ docker_registry_name }}:5000"
key_length: "4096"
key_name: "msa"
valid_time: "365"
company_name: "Test company"
company_country: "US"

# deployment type
registry_role: "undefined"

#docker
docker_registry_tar: "/opt/docker_private_registry/roles/docker_registry/files/registry.tar"
docker_custom_tars_path: "/opt/docker_private_registry/roles/docker_registry/files/custom"