- debug: var=groups['elasticsearch_nodes']


#- debug: var=hostvars['pr1']
#- debug: var=hostvars['pr2']['ansible_default_ipv4']
#- debug: var=hostvars['pr3']['ansible_default_ipv4']['address']


- set_fact:
    nodes_ip_addr_list: "{% set IP_ARR=[] %}{% for host in groups['elasticsearch_nodes'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_default_ipv4']['address']) %}{% endif %}{% endfor %}{{IP_ARR}}"


- debug: var=nodes_ip_addr_list

- name: Create ElasticSerach Config File
  template:
    src=elasticsearch.yml
    dest="{{ es_config_dir }}/elasticsearch.yml"
    owner="{{ elastic_search_user_id }}"
    group="{{ elastic_search_group_id }}"
    mode=0755
  notify:
    restart_elasticsearch_docker


- name: Create ElasticSerach Config Log File
  template:
    src=logging.yml
    dest="{{ es_config_dir }}/logging.yml"
    owner="{{ elastic_search_user_id }}"
    group="{{ elastic_search_group_id }}"
    mode=0755

