---
- name: Refresh config | Create etcd config file
  template:
    src: etcd.j2
    dest: /etc/etcd.env
  notify: restart etcd
  when: is_etcd_master

- name: Refresh config | Create etcd-proxy config file
  template:
    src: etcd-proxy.j2
    dest: /etc/etcd-proxy.env
  notify: restart etcd-proxy
  when: is_etcd_proxy
