---
- name: Preconfigure | debug download
  debug: var=download

- name: Create dest directories
  file: path={{local_release_dir}}/{{download.dest|dirname}} state=directory recurse=yes
  when: "{{ download.enabled|bool and not download.container|bool }}"

- name: Synchronize downloaded archives
  synchronize:
    src: "{{local_artifactory_dir}}/{{download.dest}}"
    dest: "{{local_release_dir}}/{{download.dest}}"
    mode: push
    recursive: yes
  register: get_task
  until: get_task|success
  retries: 8
  delay: "{{ retry_stagger | random + 3 }}"
  when:  download.enabled|bool and not download.container|bool


- name: Extract archives
  unarchive:
    src: "{{ local_release_dir }}/{{download.dest}}"
    dest: "{{ local_release_dir }}/{{download.dest|dirname}}"
    owner: "{{ download.owner|default(omit) }}"
    mode: "{{ download.mode|default(omit) }}"
    copy: no
  when: "{{ download.enabled|bool and not download.container|bool and download.unarchive is defined and download.unarchive == True }}"

- name: Fix permissions
  file:
    state: file
    path: "{{local_release_dir}}/{{download.dest}}"
    owner: "{{ download.owner|default(omit) }}"
    mode: "{{ download.mode|default(omit) }}"
  when: "{{ download.enabled|bool and not download.container|bool and (download.unarchive is not defined or not download.unarchive|bool ) }}"

#NOTE(bogdando) this brings no docker-py deps for nodes
- name: Pull containers from registry
  command: "/usr/bin/docker pull {{ download.repo }}:{{ download.tag }}"
  register: pull_task_result
  until: pull_task_result.rc == 0
  retries: 8
  delay: "{{ retry_stagger | random + 3 }}"
  when: "{{ download.enabled|bool and download.container|bool }}"
  delegate_to: "{{ groups['kube-master'][0] if download_run_once|bool else inventory_hostname }}"
  run_once: "{{ download_run_once|bool }}"

- set_fact:
    fname: "{{local_release_dir}}/containers/{{download.repo|regex_replace('/|\0|:', '_')}}:{{download.tag|regex_replace('/|\0|:', '_')}}.tar"

- name: "Set default value for 'container_changed' to false"
  set_fact:
    container_changed: false

- name: "Update the 'container_changed' fact"
  set_fact:
    container_changed: "{{ not 'up to date' in pull_task_result.stdout }}"
  when: "{{ download.enabled|bool and download.container|bool }}"
  delegate_to: "{{ groups['kube-master'][0] if download_run_once|bool else inventory_hostname }}"
  run_once: "{{ download_run_once|bool }}"