- name: Install keepalived
  apt: name=keepalived state=present # requires internet for now
  tags: keepalived
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Install keepalived
  package: name=keepalived state=present # requires internet for now
  tags: keepalived
  when: ansible_distribution == 'CentOS'
