---
dependencies:
  - role: settings
  - role: kargo_preconfigure
    file: "{{ downloads.calico_cni }}"
    tags: download
  - role: kargo_preconfigure
    file: "{{ downloads.calico_node }}"
    tags: download
  - role: kargo_preconfigure
    file: "{{ downloads.calicoctl }}"
    tags: download
  - role: kargo_preconfigure
    file: "{{ downloads.hyperkube }}"
    tags: download
