- name: Check if Gluster installed
  shell: rpm -qa | grep -q {{ item }}
  with_items:
    - glusterfs
    - glusterfs-server
    - python-gluster
    - glusterfs-cli
    - glusterfs-api
    - glusterfs-fuse
  register: package_installed
  failed_when: package_installed.rc != 0
  when: ansible_os_family == "RedHat"

- name: Disable Firewall
  service:
    name: firewalld.service
    state: stopped
    enabled: no
  when: ansible_distribution == 'CentOS'


- name: GlusterFS service
  service:
    name: glusterd.service
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS'
