- set_fact:
    docker_registry_tar_dir: "{{ docker_registry_tar|dirname }}"

- debug: var=docker_registry_tar_dir

- name: Docker custom tars dir
  file:
    path: "{{ docker_registry_tar|dirname }}"
    state: directory
    mode: 0755
    recurse: true

- name: upload docker registry image file
  copy:
    src: files/custom/registry.tar
    dest: "{{ docker_registry_tar }}"



- name: Load docker registry image from tar
  shell: 'docker load < {{ docker_registry_tar }}'
