---
- name: Ensure certs directory on host exist
  file: path={{ registry_certs_path }} state=directory
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure docker certs directory on clients exist
  file: path=/etc/docker/certs.d/{{ container_address }} state=directory

- name: Copy Cert to Docker Registry Server to /etc
  copy:
    src: "files/{{ key_name }}.crt"
    dest: "{{ registry_certs_path }}/{{ key_name }}.crt"

- name: Copy Cert Key to Docker Registry Server to /etc
  copy:
    src: "files/{{ key_name }}.key"
    dest: "{{ registry_certs_path }}/{{ key_name }}.key"

- name: Copy Cert to Docker Registry Server
  copy:
    src: "files/{{ key_name }}.crt"
    dest: "/etc/docker/certs.d/{{ container_address }}/{{ key_name }}.crt"


- name: Copy Cert Key to Docker Registry Server
  copy:
    src: "files/{{ key_name }}.key"
    dest: "/etc/docker/certs.d/{{ container_address }}/{{ key_name }}.key"


- name: Create symlink /etc
  file:
    src: "{{ registry_certs_path }}/{{ key_name }}.crt"
    dest: "{{ registry_certs_path }}/{{ key_name }}.cert"
    state: link

- name: Create symlink
  file:
    src: "/etc/docker/certs.d/{{ container_address }}/{{ key_name }}.crt"
    dest: "/etc/docker/certs.d/{{ container_address }}/{{ key_name }}.cert"
    state: link
