---
# Load available images in folder files/custom

- name: Get list of images
  shell: "ls -1 {{ role_path }}/files/custom/*.tar"
  register: docker_images
  delegate_to: localhost
  connection: local

- name: Debug
  debug: var=docker_images.stdout_lines

- name: Ensure docker images dir exists
  file: path=/opt/docker_images state=directory # gluster volume ???

- name: Upload Images
  copy:
    src: "{{ item }}"
    dest: "/opt/docker_images/{{ item|basename }}"
  with_items: '{{ docker_images.stdout_lines | default([]) }}'

- name: Load docker images from tars
  shell: docker load < "/opt/docker_images/{{ item|basename }}"
  register: loaded_images
  with_items: '{{ docker_images.stdout_lines | default([]) }}'

- name: Register loaded images names
  set_fact: 
    image_item: "{{ item.stdout| regex_replace('Loaded image\\: ', '') }}"
  with_items: "{{loaded_images.results }}"
  register: load_result

- name: Make list with docker images names for taging with private registry
  set_fact: loaded_images_names="{{ load_result.results | map(attribute='ansible_facts.image_item') | list }}"

- name: Loaded images
  debug: var=loaded_images_names

- name: Tag image for private registry
  shell: docker tag "{{ item }}"  "{{ container_address }}/{{item}}"
  with_items: '{{ loaded_images_names | default([]) }}'

- name: Push images to private registry # for using push from docker_image - ansible 2.2 required
  shell: "docker push {{ container_address }}/{{item}}"
  with_items: '{{ loaded_images_names | default([]) }}'